# Generated by Django 5.1.7 on 2026-07-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('player_limit', models.IntegerField(default=6)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(default='#10B981', max_length=20)),
                ('coins', models.IntegerField(default=5000)),
                ('starting_coins', models.IntegerField(default=5000)),
                ('captain', models.CharField(blank=True, max_length=100, null=True)),
                ('coach', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('base_price', models.IntegerField(default=100)),
                ('sold_price', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(default='Upcoming', max_length=20)),
                ('ranking', models.IntegerField(blank=True, default=0, null=True)),
                ('seed', models.IntegerField(blank=True, default=0, null=True)),
                ('auction_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='auction.category')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad', to='auction.team')),
            ],
        ),
        migrations.CreateModel(
            name='BidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_placed', to='auction.team')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_name', models.CharField(default='Ace Smashers Grand Auction', max_length=150)),
                ('tournament_name', models.CharField(default='Lawn Tennis Championship 2026', max_length=150)),
                ('sport_name', models.CharField(default='Lawn Tennis', max_length=100)),
                ('starting_coins', models.IntegerField(default=5000)),
                ('timer', models.IntegerField(default=30)),
                ('bid_increments', models.CharField(default='10,20,50,100', max_length=100)),
                ('currency_name', models.CharField(default='Coins', max_length=50)),
                ('currency_icon', models.CharField(default='💰', max_length=20)),
                ('highest_bid', models.IntegerField(default=0)),
                ('timer_remaining', models.IntegerField(default=30)),
                ('auction_status', models.CharField(default='READY', max_length=20)),
                ('current_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.category')),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_auction', to='auction.player')),
                ('highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_bids', to='auction.team')),
            ],
        ),
    ]
